import { OrgAdminReservations, Reservation } from "@/components/admin/employee-reservations";


 const reservations: Reservation[]  = [
   {
     id: "1",
     employee: "John Doe",
     email: "john.doe@bitcot.com",
     department: "HR",
     space: "Conference Room A",
     spaceType: "Conference Room",
     date: "Dec 12, 2025",
     startTime: "9:00 AM",
     endTime: "11:00 AM",
     status: "Pending",
     purpose: "Team Meeting",
     attendees: 10,
   },
   {
     id: "2",
     employee: "Sarah Williams",
     email: "sarah.w@bitcot.com",
     department: "Engineering",
     space: "Meeting Room B",
     spaceType: "Meeting Room",
     date: "Dec 12, 2025",
     startTime: "2:00 PM",
     endTime: "3:30 PM",
     status: "Pending",
     purpose: "Sprint Planning",
     attendees: 8,
   },
   {
     id: "3",
     employee: "Mike Johnson",
     email: "mike.j@bitcot.com",
     department: "Sales",
     space: "Auditorium",
     spaceType: "Auditorium",
     date: "Dec 13, 2025",
     startTime: "10:00 AM",
     endTime: "12:00 PM",
     status: "Approved",
     purpose: "Product Launch",
     attendees: 50,
   },
   {
     id: "4",
     employee: "Emily Davis",
     email: "emily.d@bitcot.com",
     department: "Marketing",
     space: "Training Room",
     spaceType: "Training Room",
     date: "Dec 13, 2025",
     startTime: "3:00 PM",
     endTime: "5:00 PM",
     status: "Approved",
     purpose: "Workshop",
     attendees: 20,
   },
   {
     id: "5",
     employee: "David Chen",
     email: "david.c@bitcot.com",
     department: "IT",
     space: "Conference Room B",
     spaceType: "Conference Room",
     date: "Dec 10, 2025",
     startTime: "11:00 AM",
     endTime: "12:00 PM",
     status: "Rejected",
     purpose: "Technical Discussion",
     attendees: 6,
   },
 ];

export default function EmployeeReservationsPage() {
    return <OrgAdminReservations reservations={reservations}/>
}